-- Which sales agents generate the highest closed-won revenue?
select s.sales_agent,s.deal_stage,max(a.revenue) as total_revenue
	from sales_pipeline s
    inner join accounts a
    on s.account = a.account
    where s.deal_stage = 'won'
    group by
		s.sales_agent,
        s.deal_stage
    order by total_revenue desc;
    
-- Which sales agents have the highest number of won opportunities?
select sales_agent,count(deal_stage) as highest_value from sales_pipeline
	where deal_stage = 'won'
    group by 
		sales_agent,
        deal_stage
    order by highest_value desc
    limit 10;
    
-- Which sales agents have the highest win rate?
with win_rate as
( 	select sales_agent,count(case when deal_stage = 'won' then 1 end ) as total_won,
		count(*) as total_count from sales_pipeline	
        group by sales_agent
)
select sales_agent,total_won*100/total_count as high_rate from win_rate
	order by high_rate desc
    limit 5;

-- What is the average deal value generated by each sales agent?
select * from sales_pipeline;
with avg_deal as
( select sales_agent,avg(close_value) as avg_value from sales_pipeline
	group by sales_agent
)
select * from avg_deal;

-- Which sales agents have the largest total pipeline value?
select sales_agent,sum(close_value) as value from sales_pipeline
	group by sales_agent
    order by value desc
    limit 5 ;

-- Which sales agents have the longest average sales cycle?
select sales_agent,avg(datediff(close_date,engage_date)) as longest_avg_sales_cycle from sales_pipeline
	group by sales_agent
    order by longest_avg_sales_cycle desc;

-- How does each sales agent's performance compare with their regional office?
select * from sales_pipeline;
select * from sales_teams;
select s.sales_agent,t.regional_office,sum(s.close_value) as agent_performance,
	avg(sum(s.close_value)) over(partition by t.regional_office) as regional_avg_performance,
    sum(s.close_value)- avg(sum(s.close_value)) over(partition by t.regional_office) as diff_from_regional_avg
	from sales_pipeline s
    inner join sales_teams t
    on s.sales_agent = t.sales_agent
    group by 
		s.sales_agent,
        t.regional_office
	order by
        t.regional_office,
        agent_performance desc;